// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHYXZjFHFbA2lcebvRJPI4xk2lvheeMs8',
    appId: '1:167036120996:web:34c691425de47236609b31',
    messagingSenderId: '167036120996',
    projectId: 'salon-ca7b6',
    authDomain: 'salon-ca7b6.firebaseapp.com',
    storageBucket: 'salon-ca7b6.appspot.com',
    measurementId: 'G-8LT7J1B019',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApoffmjG7OXif0lGaOjJ6cU5870wdxBss',
    appId: '1:167036120996:android:a7eda2c26b000471609b31',
    messagingSenderId: '167036120996',
    projectId: 'salon-ca7b6',
    storageBucket: 'salon-ca7b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwZOI4477qe1YXFcLvi89TLYnumZomlXk',
    appId: '1:167036120996:ios:283e22827331cb8f609b31',
    messagingSenderId: '167036120996',
    projectId: 'salon-ca7b6',
    storageBucket: 'salon-ca7b6.appspot.com',
    iosBundleId: 'com.example.salon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwZOI4477qe1YXFcLvi89TLYnumZomlXk',
    appId: '1:167036120996:ios:98a0df05ce8b4d90609b31',
    messagingSenderId: '167036120996',
    projectId: 'salon-ca7b6',
    storageBucket: 'salon-ca7b6.appspot.com',
    iosBundleId: 'com.example.salon.RunnerTests',
  );
}
